services:
  db1:
    image: postgres:16.1
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres1:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10 
  db2:
    image: postgres:16.1
    ports:
      - "5433:5432"
    volumes:
      - ./volumes/postgres2:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10 